### ISSUE TITLE
Can you let me know how to extract speech representations?

### ISSUE THREAD

**Issue by homechilling** [MingjieChen/wavenet_autoencoders#2]
Thank you for the repo. It is very well organized.

Through a lot of setting-up, I got the networks trained. I used the command "bash ./run_bash/run_inae_train.sh exp_name hps/inae_hp.json english".

If possible, can you let me know how to extract speech representations/features? I am planning to use the features for ZeroSpeech2017 ABX tests. Much appreciated.

**Comment by MingjieChen** [comment]
Hello, 

I do have a script for preprocessing on 2017 dataset, but it was long time ago, I can't be sure that it will work.

However, I don't have enough time to test my script for now. 

If you are urgent, I am sorry I can't help for now.
if you can wait until October, I can update the script.

**Comment by homechilling** [comment]
> Hello,
> 
> I do have a script for preprocessing on 2017 dataset, but it was long time ago, I can't be sure that it will work.
> 
> However, I don't have enough time to test my script for now.
> 
> If you are urgent, I am sorry I can't help for now.
> if you can wait until October, I can update the script.

Thank you for the quick reply.

Your own work is definitely more prioritized. I can wait. Much appreciated.

**Comment by homechilling** [comment]
Thank you again for the repo. Hope your project is going well.

I have been studying the training scripts carefully. Perhaps my experience with DNNs is too little. I haven't been able to come up with a working script to extract speech representations from the trained nets. 

If possible, could you shed some light on how to extract the representations? Any past example or online resource would be appreciated. Thank you a lot.

**Comment by MingjieChen** [comment]
Hi,  I am trying to help you now, but I need more details about what you want to do. 
As I understand, at this point, you just need to run bash script run_infer19.sh

**Comment by homechilling** [comment]
Thank you for the quick reply.

I honestly haven't studied run_infer19.sh yet. I will look at it now. I have been trying to do the ABX tests (subword modelling task, since ZeroSpeech2017) and I have the ABX program working already (with baseline MFCCs as of yet). I understand I need to extract feature files from the DNNs and feed them to the ABX program. It's possible the run_infer19.sh can get me started for feature extraction. I'll let you know. 

Thank you again.

**Comment by homechilling** [comment]
Hope you are enjoying the holidays.
I was able to infer the features following your instruction. Thank you and happy new year.
Best wishes
